apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

jobs:
  deploy:
    steps:
      - name: Login AWS
        uses: cloudbees-io/configure-aws-credentials@v0
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ vars.cloudbees_saas_test_access_key_id }}
          aws-secret-access-key: ${{ secrets.cloudbees_saas_test_secret_access_key }}
          role-to-assume: service-eks-role
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max
      - name: Print CLI versions
        uses: docker://swashbuck1r/quickstart-tools:0.0.1
        shell: bash
        run: |
          set -x +e
          aws sts get-caller-identity
          


      # - uses: cloudbees-io/configure-eks-credentials@v0
      #   with:
      #     name: arch-saas

      # - uses: cloudbees-io/configure-ecr-credentials@v0

      # - uses: docker://alpine/helm:latest
      #   run: |
      #     helm upgrade \
      #       --namespace simple-api \
      #       --create-namespace \
      #       --install \
      #       --version ${{ needs.build.outputs.chart-version }} \
      #       app-chart ${{ needs.build.outputs.chart-location }}