apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Workflow

on:
  push:
    branches:
      - '**'

jobs:
  build-and-publsh:
    steps:
      - name: checkout code
        uses: cloudbees-io/checkout@v1

      - name: Setup Dockerhub container registry
        uses: cloudbees-io/configure-oci-credentials@v1
        with:
          registry: index.docker.io # or docker.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push container image to registry
        uses: cloudbees-io/kaniko@v1
        with:
          destination: ${{ vars.DOCKERHUB_USERNAME }}/quickstart-tools:${{ cloudbees.version }}
  
